version: 2.1
jobs:
  build:
    docker:
      - image: checkmarx/ast-cli
    steps:
      - checkout
      - run:
          name: "Run Scan"
          command: |
            /app/bin/cx scan create --project-name AASMACMX/Apex_Aalbert_Vulnerable_Code -s ./ --branch master --agent Intellij base-uri $CX_BASE_URI base-auth-uri $CX_BASE_AUTH_URI tenant $CX_TENANT --client-id $CX_CLIENT_ID client-secret $CX_CLIENT_SECRET
